### ISSUE TITLE
Please have a proper LICENSE file

### ISSUE THREAD

**Issue by richardanaya** [ubercomp/jslm32#4]
I found the file named COPYING really hard to recognize as the file to figure out what the code was licensed under.

**Comment by ysangkok** [comment]
[`COPYING` is the standard GNU license file name](http://stackoverflow.com/a/5678716/309483), I don't see a problem with it, but there might as well be a short notice in the `README` saying it is LGPL 2.1.

**Comment by richardanaya** [comment]
Oh! Interesting, I think i am just used to seeing LICENSE in peoples project.  It would be cool to see it in the project description at the top too.  But that's just personal preference.

**Comment by ubercomp** [comment]
Closed by commit https://github.com/ubercomp/jslm32/commit/82df525eb687b786b76118efc341e5f371bf34b2
