### ISSUE TITLE
Use a better terminal emulation library

### ISSUE THREAD

**Issue by ysangkok** [ubercomp/jslm32#5]
I propose:
- http://www.masswerk.at/termlib/ (referenced by Fabrice Bellard on his tech details page)
- https://github.com/chjj/term.js (**my favorite**)
- http://mister-muffin.de/scriptreplay/VT100.js (outdated by now, IMHO)

**Comment by ubercomp** [comment]
Done. Ended up using http://bellard.org/riscvemu/js/term.js
